version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 32814:52773
      - 53773
    volumes:
      - ./:/irisrun/repo